security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: login
        check_path: login
        default_target_path: demo_home
        enable_csrf: true
      logout:
        path: logout
        target: login
      login_throttling:
        max_attempts: 3
        interval: '10 minutes'
        limiter: nowo_login_throttle.database_rate_limiter.shared_3_600s_3600s
    api:
      pattern: ^/api
      lazy: true
      provider: app_user_provider
      stateless: true
      json_login:
        check_path: api_login
        username_path: email
        password_path: password
      login_throttling:
        max_attempts: 5
        interval: '5 minutes'
        limiter: nowo_login_throttle.database_rate_limiter.shared_5_300s_3600s
    admin:
      pattern: ^/admin
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: admin_login
        check_path: admin_login
        default_target_path: admin_home
        failure_path: admin_login
        enable_csrf: true
      logout:
        path: admin_logout
        target: admin_login
      login_throttling:
        max_attempts: 3
        interval: '30 minutes'
        limiter: nowo_login_throttle.database_rate_limiter.shared_3_1800s_3600s
  access_control:
    -
      path: ^/$
      roles: PUBLIC_ACCESS
    -
      path: ^/login
      roles: PUBLIC_ACCESS
    -
      path: ^/api/login
      roles: PUBLIC_ACCESS
    -
      path: ^/admin/login
      roles: PUBLIC_ACCESS
    -
      path: ^/home
      roles: ROLE_USER
    -
      path: ^/api
      roles: ROLE_USER
    -
      path: ^/admin
      roles: ROLE_ADMIN
    -
      path: ^/
      roles: ROLE_USER
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
